/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.joefox.prime;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;

public class AppTest {

    private App app;

    @BeforeEach public void init() {
        this.app = new App();
    }

    @Test public void testGetGreetingReturnsHelloWorld() {
        assertEquals("Hello world.", this.app.getGreeting());
    }

    @Test public void testGetInstanceReturnsApp() {
        App newInstance = App.getInstance();
        assertTrue(newInstance instanceof App);
        assertEquals(newInstance, App.getInstance());
    }
}
